- name: Demo on loops
  hosts: localhost
  tasks:
    - name: loop
      ansible.builtin.debug:
        msg: Fruit - {{item}}
      loop:
        - apple
        - banana
        - orange

- name: Demo on loops
  hosts: localhost
  vars:
    fruits:
      - apple
      - banana
      - orange
  tasks:
    - name: loop
      ansible.builtin.debug:
        msg: Fruit - {{item}}
      loop: "{{fruits}}"

- name: Demo on loops - map
  hosts: localhost
  vars:
    fruits:
      - apple
      - banana
      - orange
  tasks:
    - name: loop
      ansible.builtin.debug:
        msg: Fruit Name - {{item.name}}, Quantity - {{item.quantity}}
      loop:
        - {name: "apple", quantity: 100}
        - {name: "banana", quantity: 300}
        - {name: "grapes", quantity: 200}